In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv(r'C:\Users\pankaj\Downloads\coaching\project1\Final_Dataset.csv')

In [2]:
data

,sex,Age,children,Smoker,bmi,education,income,Distinct_Parties_on_Claim,Type_of_insurance,Policy_Length,...,Claim_Cancellation,Brand_credibility_,Claim_After_Renewal,Contracted_care_,Experience_during_contact_moment,Premium_price_,Outstanding_charges,Discount,Deductible_excess_,Renewal
0,0,18,0,1,27.4,1,800000.0,1,2,1,...,0,3,0,0,2,3000,847.0,0,0,0
1,1,18,0,0,42.5,1,425000.0,1,2,1,...,0,3,0,0,5,7000,265.0,0,0,1
2,1,18,0,0,52.4,1,325000.0,0,1,2,...,0,4,0,0,4,19000,1008.0,0,0,0
3,0,19,0,0,57.7,1,875000.0,0,2,1,...,0,3,2,2,3,31000,704.0,0,0,1
4,0,19,0,1,29.8,0,1150000.0,1,0,1,...,0,3,2,2,1,42000,2530.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,62,2,0,19.2,1,2000000.0,1,2,2,...,0,3,1,0,1,9000,1536.0,0,0,0
996,0,74,2,0,20.5,1,2200000.0,0,2,1,...,0,4,0,0,5,3000,2310.0,0,0,1
997,0,59,3,0,22.7,1,650000.0,1,0,2,...,0,3,5,2,3,42000,897.0,0,0,0
998,0,48,1,0,22.1,1,1600000.0,1,0,2,...,0,4,1,2,3,44000,1575.0,0,0,0
999,0,22,3,0,21.1,1,1875000.0,0,3,3,...,0,3,0,1,1,29000,1155.0,0,0,0

In [3]:
data.columns

Index(['sex', 'Age', 'children', 'Smoker', 'bmi', 'education', 'income',
       'Distinct_Parties_on_Claim', 'Type_of_insurance', 'Policy_Length',
       'Claim_Type', 'Payment_method_', 'Number_of_declarations',
       'Number_of_authorizations_',
       'Handling_time_of_authorizations_and_declarations_',
       'Duration_of_current_insurance_contract',
       'Elapsed_time_since_last_contact_moment', 'Product_usage_',
       'Elapsed_time_since_the_last_complaint', 'Policy_Claim_Day_Diff',
       'Claim_History', 'Renewal_History', 'Customer_Complaint',
       'Number_of_complaints',
       'Customer_mentioned_that_they_are_going_to_switch',
       'Switching_barrier_', 'Claim_Cancellation', 'Brand_credibility_',
       'Claim_After_Renewal', 'Contracted_care_',
       'Experience_during_contact_moment', 'Premium_price_',
       'Outstanding_charges', 'Discount', 'Deductible_excess_', 'Renewal'],
      dtype='object')

In [4]:
from sklearn.preprocessing import scale
df_scale=scale(data)

In [5]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np

pca=PCA(n_components=(35)) #Principal component on 35 columns
pca_values=pca.fit_transform(df_scale)
var=pca.explained_variance_ratio_
var1=np.cumsum(np.round(var,decimals=4)*100)
print("Variance Ratio: ",var1)

Variance Ratio:  [  9.2   15.96  21.08  25.95  30.22  33.98  37.48  40.84  44.13  47.34
  50.53  53.65  56.7   59.69  62.58  65.46  68.23  70.96  73.64  76.27
  78.9   81.43  83.87  86.27  88.57  90.75  92.71  94.2   95.48  96.61
  97.54  98.36  99.15  99.91 100.02]

In [6]:
pca_values
type(pca_values)
pca_data = pd.DataFrame(pca_values)

#Naming the PCA columns
name=[]
for i in range(1,36):
    a="PC"+str(i)
    name.append(a)
pca_data.columns =name 

#Considering only 26 PCA as they it summraise the 91% of the data, so dropping 9 PCA
final = pd.concat([pca_data.iloc[:, 0:26],data.Renewal], axis = 1)

In [7]:
x=data.iloc[:,0:25]
y=data["Renewal"]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

from sklearn.tree import DecisionTreeClassifier as DT
model_decision = DT(criterion = 'entropy')
model_decision.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [10]:
pred=model_decision.predict(x_test)

In [11]:
import pickle
pickle.dump(model_decision,open('excute.pkl','wb'))
model=pickle.load(open('excute.pkl','rb'))